modLoader="javafml"
loaderVersion="[47,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="spelunker_lite"
version="1.0.0"
displayName="Spelunker lite"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="mosyusi/sansyoouo"
description="A simplified version of the Spelunker mod co-developed for mosyusi's Minecraft modpack."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.spelunker_lite]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration